services:
  php:
    build:
      context: .
      target: frankenphp_dev
    environment:
      APP_ENV: test
      EXPERTM_UID: 999
      EXPERTM_GID: 998
    volumes:
      - ./:/app
      - vendor_data:/app/vendor
      - vendor_tools_phpcs:/app/tools/php-cs-fixer/vendor
      - vendor_tools_phpstan:/app/tools/phpstan/vendor
      - vendor_tools_psalm:/app/tools/psalm/vendor
    ports:
      - '${HTTP_PORT:-80}:80/tcp'
      - '${HTTPS_PORT:-443}:443/tcp'
      - '${HTTP3_PORT:-443}:443/udp'

  database:
    environment:
      - MYSQL_DATABASE=${DB_NAME?}_test

volumes:
  vendor_data:
  vendor_tools_phpcs:
  vendor_tools_phpstan:
  vendor_tools_psalm:
